# A credencial inteira é uma única string de múltiplas linhas
gcp_service_account = """
{
  "type": "service_account",
  "project_id": "portal-471100",
  "private_key_id": "27d1ed2fcc9b4165b2661534eb45738f5878086c",
  "private_key": "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9iiRs5hGfTim9
PwvH01teOOtCuxlVdy0swUcnOeeqS6wWBTJCrV9GfDhyEBQUY5UzEDq7tgJ113gQ
xqjxXKOjcqEX/LdIVZMEy/2zzFanPsrJdrsZuBJKfQFnqk4WUup1qc9syl0JjU89
XsGH1MW9Ei/8UQcKwXWihU55RFcXYTJwFrTu2vYKIXr7V4JtnUJZK1dBZsByxdtn
0UH9qSIybM4q91EsgOyIYNaWidvgboT2bYMNZGOauO5V868bYyzla4wbRue/6Vzh
eVszS++56GxjykD/d56n3Wfp44SIayXsMfCUVr6v2sckm7egMneMI0UxtHZLaCi4
7LELUfptAgMBAAECggEAArVdJOM6wDyFMyuZ9v6JsTR+BCOZTpPX5OpUInbc3R2c
tWnYmIRStraitdqN9uafZK3oMPN+YIG2OQMlueE5g2XpcGbPlayHX8uscevLFzO6
ARv9u3XaaQ8VPI599Cq2J/1HtgXEQ5Ut2zIl8NN1CekfH2tm/tvZ2vstrmTwG6jl
GCONluunQdPIjE9bsfgSmQxCEAyH/HEVN/aniAiegHa33wKvL/OtuczuNUajUY1Q
lrjZ1Bm0wEAMnBbzk7OtAMMw7fMQ3/MyubhCVcTUW+0iA/m2v29KKqIcWbi8oSgp
yQ743K1Rx40YopnJPc0H1n3hIduhewvX9cGT6u/8EQKBgQDtC5XCIvAawsIFu2UX
kuxRZWlv9VXW/Pro0Bcw8sH+7LlbiJ7RUs1W/Wos9YNcrVwsTZKody75+VqDQ75a
Gos4uqzuj1d2BXzb2tTCT9Hsi46G0Yd+nnq1QH/INasUcQqFth45Z1SOov6MWuQR
Ks9PuAYuGnPAx4gv4a+XEQRPRQKBgQDMshjfiDHhkkMQFOssB3Le4KloX/7cWKlH
3ia6ViwDrT5b4gXkIrmMqhVpvlEZDFribAyXWptqdl6X3Sj8QbJynK6STO1yRUYv
lm8BB8nMTYQlge7p+aX0xOpFZ6gCOvh9+xkRV+BNm7lTVhu+FItNIsgKuY5ADzLv
PvfB88T9CQKBgHt4BVFRkW7e8uC5czaMOLtM71Z5m3SX4LlTakD8sT9vXjznNJIj
ZwFgjeVNHFcxlUkePr2xFq7tys+EgamdGbc6xMidsRiwUxDRMvDjUpy7NEnU6ZZy
RcgTCHvoOGw1VR3Ado2/3LNPAvdogFLQ0ZrcZ5ur+472X2FRVHyDSJNhAoGBAIfD
W+HuR/8vbhFdfnkOW67dXR7gBH6Kw4PqIM+X1ct+fQyeBYBBU8WrDVa8JrexTRo9
xcAhFVFwPt8EjWl5/Wws5VAde6M9tQZdBTSuwLYjd5EU86v1q4+Dh0oPLQyFpkiQ
YRjyqs9uiGVwiCfzIk0/02PhnCp6qjKqFdNq5e1ZAoGAabqlIOOnZQw7B7YQIzfr
YMnJN3Avwj7cJoef2N9SUaixVjeJdaM8VNA2o0B/ot0qDaFn8AEuOyhB9vyPrVUH
hp/UuTMr8AyfjEi0PqM+4wXVvN97wmq3J4Oz9rnswVOLuAovNlrVQeQFpB2jLk53
vgBWtcXZpBfF2XfSDZXMOfo=
-----END PRIVATE KEY-----",
  "client_email": "painel@portal-471100.iam.gserviceaccount.com",
  "client_id": "117590605560138979552",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/painel%40portal-471100.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

# As outras variáveis podem continuar separadas
sheet_id = "11pL27tZ_N6j5iwQ2IVFG9aKwjGOxnmD94-7URlByV7c"
