url = "https://lncosjwzjedypshlnawa.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuY29zand6amVkeXBzaGxuYXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTY1OTYsImV4cCI6MjA3Mjc3MjU5Nn0.qlCw-vEHOOqLpGU2bzO4y2hLe8RAwY9ZrCpuyeC0wqQ"
